# Generated by Django 4.1.1 on 2022-10-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0002_about_contacto_latestwork"),
    ]

    operations = [
        migrations.AddField(
            model_name="comunidad",
            name="imagen",
            field=models.ImageField(null=True, upload_to="imagen"),
        ),
    ]
