# Generated by Django 4.1.1 on 2022-10-21 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0003_comunidad_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comunidad",
            name="imagen",
        ),
    ]
